# Generated by Django 4.0.3 on 2022-05-12 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('middlename', models.CharField(default='middle_name', max_length=300)),
                ('nif', models.IntegerField(default=0)),
                ('address', models.CharField(default='address', max_length=400)),
                ('city', models.CharField(default='city', max_length=150)),
                ('postalcode', models.CharField(default='0000-000', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
