# Generated by Django 4.0.3 on 2022-04-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vehicle',
            field=models.CharField(choices=[('TES', 'Tesla'), ('MAZ', 'Mazda'), ('VOL', 'Volvo')], default='TES', max_length=9),
        ),
    ]
