# Generated by Django 3.2.13 on 2022-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vehicle',
            field=models.CharField(choices=[('TESLA', 'Tesla'), ('MAZDA', 'Mazda'), ('VOLVO', 'Volvo')], default='TESLA', max_length=9),
        ),
    ]
