# Generated by Django 4.0.3 on 2022-04-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vehicle',
        ),
    ]
