# Generated by Django 4.0.3 on 2022-05-05 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='new_charge',
        ),
    ]
