# Generated by Django 4.0.4 on 2022-05-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chargers', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chargers',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chargers.chargers'),
        ),
    ]
