# Generated by Django 3.2.13 on 2022-04-30 14:00

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.edit


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_vehicle'),
        ('blog', '0002_remove_post_content_remove_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCreateView',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.profile')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, django.views.generic.edit.CreateView, 'users.profile'),
        ),
    ]
