# Generated by Django 4.0.3 on 2022-05-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('blog', '0005_delete_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle'),
        ),
    ]
