# Generated by Django 4.0.3 on 2022-05-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_vehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostCreateView',
        ),
    ]
