# Generated by Django 4.0.3 on 2022-05-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicle',
            table='vehicles',
        ),
    ]
