# Generated by Django 4.0.3 on 2022-05-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
        migrations.AlterModelTable(
            name='vehicle',
            table='Vehicle',
        ),
    ]
